### PR TITLE
For #42, Add index column to requestList

### PR DESCRIPTION
**Pull request by gitgrimbo**
Hi, this PR is a tentative step to adding an index column to `RequestList`.  I say tentative because I'm still not totally familiar with domplate, so I could be using it inappropriately.

Would appreciate any comments and tips. Cheers!

---

The index can be output in one of two formats:
- "page" - index is composite of page number and entry number.
  e.g. "1.1", "1.2", ... "2.1", "2.2", etc.
- "entry" - index is simple, flat index.
  e.g. "1", "2", etc.

The index type is passed to the `RequestList` constructor in an options object.

This change needed to pass multiple arguments to domplate callbacks, so
cherry-picked domplate.js changes from:
- https://github.com/firebug/firebug/commit/65d035b7814c82e5e3a9fa2a145c5117bb290f79
  (Issue 5107: Passing multiple arguments to a function in Domplate)

---

Sample:

harviewer-42

### CODE REVIEW

**Comment by bobpappas** [comment]
@gitgrimbo, does this PR add the index column to the PHP view of the HAR? I am trying out your PR with the local PHP server and I don't see it there.

**Comment by bobpappas** [comment]
@gitgrimbo, found my issue. In requestList.js RequestList.getVisibleColumns function was finding a cookie with a set of columns from the older version of harViewer. It didn't have the index column there. I cleared the cookie, and also made my local version column defaults include the index column. Phew!

**Comment by gitgrimbo** [comment]
@bobpappas that's good to hear.  I was going to add a few more features but I wanted to check (using this PR) that I was going about it in the correct way and not doing anything inappropriate.  If I get the green light I'll look to pick up this sort of work again.

**Comment by gitgrimbo** [comment]
Closed by https://github.com/janodvarko/harviewer/commit/560d41dece5f67ed9a40b77637f2374c20ff2843

**Pull request closed without merging**
